/**
 * SchemaBoolean.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package terrapeer.net.xml.types;

public class SchemaBoolean implements SchemaType {
	protected boolean value;

	public SchemaBoolean(SchemaBoolean newvalue) {
		value = newvalue.value;
	}

	public SchemaBoolean(boolean newvalue) {
		value = newvalue;
	}

	public SchemaBoolean(String newvalue) {
		value = newvalue != null && (newvalue.equalsIgnoreCase("true") || newvalue.equals("1"));
	}

	public boolean getValue() {
		return value;
	}

	public void setValue(boolean newvalue) {
		value = newvalue;
	}

	public void setValue(String newvalue) {
		value = newvalue != null && (newvalue.equalsIgnoreCase("true") || newvalue.equals("1"));
	}

	public int hashCode() {
		return value ? 1231 : 1237;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaBoolean))
			return false;
		return value == ((SchemaBoolean)obj).value;
	}

	public Object clone() {
		return new SchemaBoolean(value);
	}

	public String toString() {
		return value ? "true" : "false";
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaBoolean)obj);
	}

	public int compareTo(SchemaBoolean obj) {
		if (value == obj.value)
			return 0;
		else if (value == false)
			return -1;
		else
			return 1;
	}
}
