/**
 * SchemaInteger.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package terrapeer.net.xml.types;

import java.math.BigInteger;

public class SchemaInteger implements SchemaType {
	protected BigInteger value;

	public SchemaInteger(BigInteger newvalue) {
		value = newvalue;
	}

	public SchemaInteger(String newvalue) {
		value = new BigInteger(newvalue);
	}

	public SchemaInteger(long newvalue) {
		value = new BigInteger(Long.toString(newvalue));
	}

	public BigInteger getValue() {
		return value;
	}

	public void setValue(BigInteger newvalue) {
		value = newvalue;
	}

	public void setValue(String newvalue) {
		value = new BigInteger(newvalue);
	}

	public void setValue(long newvalue) {
		value = new BigInteger(Long.toString(newvalue));
	}

	public long longValue() {
		return Long.parseLong(value.toString());
	}

	public int hashCode() {
		return value.hashCode();
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaInteger))
			return false;
		return value.equals(((SchemaInteger)obj).value);
	}

	public Object clone() {
		return new SchemaInteger(value.toString());
	}

	public String toString() {
		return value.toString();
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaInteger)obj);
	}

	public int compareTo(SchemaInteger obj) {
		return value.compareTo(obj.value);
	}
}
