/**
 * SchemaToken.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package terrapeer.net.xml.types;

public class SchemaToken extends SchemaNormalizedString {
	public SchemaToken(String newvalue) {
		super(newvalue);
	}

	public SchemaToken(SchemaToken newvalue) {
		super((SchemaNormalizedString)newvalue);
	}
}
