/**
 * SchemaName.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package terrapeer.net.xml.types;

public class SchemaName extends SchemaToken {
	public SchemaName(String newvalue) {
		super(newvalue);
	}

	public SchemaName(SchemaName newvalue) {
		super((SchemaToken)newvalue);
	}
}
