/**
 * SchemaByte.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package terrapeer.net.xml.types;

public class SchemaByte implements SchemaType {
	protected byte value;

	public SchemaByte(int newvalue) {
		value = (byte)newvalue;
	}

	public SchemaByte(String newvalue) {
		value = Byte.parseByte(newvalue);
	}

	public byte getValue() {
		return value;
	}

	public void setValue(int newvalue) {
		value = (byte)newvalue;
	}

	public void setValue(String newvalue) {
		value = Byte.parseByte(newvalue);
	}

	public int hashCode() {
		return value;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaByte))
			return false;
		return value == ((SchemaByte)obj).value;
	}

	public Object clone() {
		return new SchemaByte(value);
	}

	public String toString() {
		return Byte.toString(value);
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaByte)obj);
	}

	public int compareTo(SchemaByte obj) {
		return new Byte(value).compareTo(new Byte(obj.value));
	}
}
