/**
 * SchemaDecimal.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package terrapeer.net.xml.types;

import java.math.BigDecimal;

public class SchemaDecimal implements SchemaType {
	protected BigDecimal value;

	public SchemaDecimal(BigDecimal newvalue) {
		value = newvalue;
	}

	public SchemaDecimal(String newvalue) {
		value = new BigDecimal(newvalue);
	}

	public SchemaDecimal(double newvalue) {
		value = new BigDecimal(Double.toString(newvalue));
	}

	public BigDecimal getValue() {
		return value;
	}

	public void setValue(BigDecimal newvalue) {
		value = newvalue;
	}

	public void setValue(String newvalue) {
		value = new BigDecimal(newvalue);
	}

	public void setValue(double newvalue) {
		value = new BigDecimal(Double.toString(newvalue));
	}

	public double doubleValue() {
		return value.doubleValue();
	}

	public int hashCode() {
		return value.hashCode();
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaDecimal))
			return false;
		return value.equals(((SchemaDecimal)obj).value);
	}

	public Object clone() {
		return new SchemaDecimal(value.toString());
	}

	public String toString() {
		return value.toString();
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaDecimal)obj);
	}

	public int compareTo(SchemaDecimal obj) {
		return value.compareTo(obj.value);
	}
}
