/**
 * SchemaLong.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package terrapeer.net.xml.types;

public class SchemaLong implements SchemaType {
	protected long value;

	public SchemaLong(long newvalue) {
		value = newvalue;
	}

	public SchemaLong(String newvalue) {
		value = Long.parseLong(newvalue);
	}

	public long getValue() {
		return value;
	}

	public void setValue(long newvalue) {
		value = newvalue;
	}

	public void setValue(String newvalue) {
		value = Long.parseLong(newvalue);
	}

	public int hashCode() {
		return (int)value;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaLong))
			return false;
		return value == ((SchemaLong)obj).value;
	}

	public Object clone() {
		return new SchemaLong(value);
	}

	public String toString() {
		return Long.toString(value);
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaLong)obj);
	}

	public int compareTo(SchemaLong obj) {
		return new Long(value).compareTo(new Long(obj.value));
	}
}
